---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r load packages}

# library(dplyr)
# library(data.table)
# library(reshape2)
# library(jagsUI)
# library(getWBData)
```

```{r load and wrangle the data}
rivers<-"wb obear"
gr<-getGrowth(rivers=rivers)
#gr<-gr[1:100]


temp<-tbl(conDplyr,"data_hourly_temperature") %>% 
  filter(river==rivers) %>%
  collect() %>% 
  data.table() %>% 
  mutate(date=as.Date(datetime)) %>%
  .[date>=min(gr$startDate)&date<=max(gr$endDate)]

gr[,':='(startTime=min(which(temp$datetime>as.POSIXct(startDate))),
      endTime=max(which(temp$datetime<as.POSIXct(endDate)))),
   by=.(tag,startDate)]

# sumOverArray<-array(0,dim=c(nrow(temp),nrow(gr)))
# for(g in 1:nrow(gr)){
#   sumOverArray[gr$startTime[g]:gr$endTime[g],g]<-1
# }

jagsData<-list(grDATA=gr$growth,
               tempDATA=temp$temperature,
               startTime=gr$startTime,
               endTime=gr$endTime,
               nTimes=nrow(temp),
               nObs=nrow(gr),
               medianLengthDATA=gr[,(startLength+endLength)/2])
#jagsData[['above85']]<-1+as.numeric(jagsData$medianLengthDATA>=92)
```

```{r make model file and fit the model}
createModel()
inits<-function(){list(ctMax=rnorm(1,20,0.5),
                       tOpt=rnorm(1,9,0.5))
}

out<-fitModel(jagsData=jagsData,inits=inits,parallel=T,nb=2000,ni=3000)
saveRDS(out,file="results/outObear.rds")
```

```{r examine results}
plot(NA,xlim=c(0,22),ylim=c(-2,1))
for(i in sample(1:length(out$sims.list$tOpt),300)){
  points(predictPerformance(0:22,tOpt=out$sims.list$tOpt[i],
                     sigma=out$sims.list$sigma[i],
                     ctMax=out$sims.list$ctMax[i])~I(0:22),
       type='l',col='gray')
}
